// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.2
// source: weather.proto

package weatherforecast

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WeatherForecastsClient is the client API for WeatherForecasts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WeatherForecastsClient interface {
	GetWeather(ctx context.Context, in *WeatherRequest, opts ...grpc.CallOption) (*WeatherReply, error)
}

type weatherForecastsClient struct {
	cc grpc.ClientConnInterface
}

func NewWeatherForecastsClient(cc grpc.ClientConnInterface) WeatherForecastsClient {
	return &weatherForecastsClient{cc}
}

func (c *weatherForecastsClient) GetWeather(ctx context.Context, in *WeatherRequest, opts ...grpc.CallOption) (*WeatherReply, error) {
	out := new(WeatherReply)
	err := c.cc.Invoke(ctx, "/WeatherForecasts/GetWeather", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WeatherForecastsServer is the server API for WeatherForecasts service.
// All implementations must embed UnimplementedWeatherForecastsServer
// for forward compatibility
type WeatherForecastsServer interface {
	GetWeather(context.Context, *WeatherRequest) (*WeatherReply, error)
	mustEmbedUnimplementedWeatherForecastsServer()
}

// UnimplementedWeatherForecastsServer must be embedded to have forward compatible implementations.
type UnimplementedWeatherForecastsServer struct {
}

func (UnimplementedWeatherForecastsServer) GetWeather(context.Context, *WeatherRequest) (*WeatherReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWeather not implemented")
}
func (UnimplementedWeatherForecastsServer) mustEmbedUnimplementedWeatherForecastsServer() {}

// UnsafeWeatherForecastsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WeatherForecastsServer will
// result in compilation errors.
type UnsafeWeatherForecastsServer interface {
	mustEmbedUnimplementedWeatherForecastsServer()
}

func RegisterWeatherForecastsServer(s grpc.ServiceRegistrar, srv WeatherForecastsServer) {
	s.RegisterService(&WeatherForecasts_ServiceDesc, srv)
}

func _WeatherForecasts_GetWeather_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WeatherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeatherForecastsServer).GetWeather(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WeatherForecasts/GetWeather",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeatherForecastsServer).GetWeather(ctx, req.(*WeatherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WeatherForecasts_ServiceDesc is the grpc.ServiceDesc for WeatherForecasts service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WeatherForecasts_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "WeatherForecasts",
	HandlerType: (*WeatherForecastsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWeather",
			Handler:    _WeatherForecasts_GetWeather_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "weather.proto",
}
